spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp    
   
  jpa: 
    hibernate: 
      ddl-auto: update  # create, update, create-drop, none 등의 옵션이 있습니다. 
                        # create: 기존테이블 삭제 후 다시 생성 
                        # update: 변경된 부분만 반영 
                        # create-drop: create와 같으나 종료 시점에 테이블 DROP 
                        # none: 사용하지 않음 
      generate-ddl: true # DDl 생성 시 데이터베이스 고유의 기능 사용여부 
      show-sql: true    # 실행되는 쿼리문 보여주기 여부 
      database: h2      # 사용되는 데이터베이스(MariaDB는 없기 때문에 mysql로 지정) 
                        # 테이블 생성시 엔진을 InnoDB 로 생성. 설정하지 않으면 myisam로 등록 
      #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true
      
  datasource:
      #type: org.apache.tomcat.jdbc.pool.DataSource
      #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #url: jdbc:log4jdbc:h2:test
      url: jdbc:h2:file:./test
      #username: sa
      #password: sa
      #schema: classpath:database/sql/greeting.sql,classpath:database/sql/ddl_*.sql
      #data: classpath:database/sql/dml_*.sql
      
logging:
  level:
    com.lyn.study.springboot: DEBUG

      
server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false      
        
